//! Input validation types and helpers.
//!
//! Provides `ValidationErrors` for accumulating field-level validation errors,
//! and small validator helper functions used by the `#[model]` macro codegen.
//!
//! The `validate()` method on model structs is auto-generated by the
//! `#[col(...)]` validation rules (len, email, url, range, regex, required).
//! This module provides the runtime types that the generated code depends on.
//!
//! # Usage
//!
//! ```ignore
//! #[route(post: "/users")]
//! async fn create_user(body: Json<User>, state: State) -> Resp {
//!     body.validate()?;  // auto 422 if validation fails
//!     // ...
//! }
//! ```

use std::collections::HashMap;

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// ValidationErrors
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

/// Accumulated per-field validation errors.
///
/// Created by the `validate()` method on `#[model]` structs.
/// Converts to `ApiError` (HTTP 422) via the `?` operator.
///
/// # JSON format
///
/// ```json
/// {
///   "error": "validation_failed",
///   "fields": {
///     "email": ["must be a valid email address"],
///     "name": ["length must be at least 1"]
///   }
/// }
/// ```
#[derive(Debug, Clone)]
pub struct ValidationErrors {
    errors: HashMap<String, Vec<String>>,
}

impl ValidationErrors {
    /// Create a new empty error accumulator.
    pub fn new() -> Self {
        Self {
            errors: HashMap::new(),
        }
    }

    /// Add a validation error for a specific field.
    pub fn add(&mut self, field: &str, message: &str) {
        self.errors
            .entry(field.to_string())
            .or_default()
            .push(message.to_string());
    }

    /// Returns true if no validation errors were recorded.
    pub fn is_empty(&self) -> bool {
        self.errors.is_empty()
    }

    /// Convert to a Result — `Ok(())` if no errors, `Err(self)` otherwise.
    pub fn into_result(self) -> Result<(), Self> {
        if self.is_empty() {
            Ok(())
        } else {
            Err(self)
        }
    }

    /// Get the inner errors map.
    pub fn errors(&self) -> &HashMap<String, Vec<String>> {
        &self.errors
    }

    /// Get errors for a specific field.
    pub fn field_errors(&self, field: &str) -> Option<&Vec<String>> {
        self.errors.get(field)
    }
}

impl Default for ValidationErrors {
    fn default() -> Self {
        Self::new()
    }
}

impl std::fmt::Display for ValidationErrors {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut first = true;
        for (field, messages) in &self.errors {
            for msg in messages {
                if !first {
                    write!(f, "; ")?;
                }
                write!(f, "{}: {}", field, msg)?;
                first = false;
            }
        }
        Ok(())
    }
}

impl std::error::Error for ValidationErrors {}

impl From<ValidationErrors> for crate::errors::ApiError {
    fn from(errors: ValidationErrors) -> Self {
        let fields_json = serde_json::to_value(errors.errors()).unwrap_or_default();
        crate::errors::ApiError {
            code: crate::errors::ErrorCode::BadRequest,
            message: serde_json::json!({
                "error": "validation_failed",
                "fields": fields_json
            })
            .to_string(),
        }
    }
}

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// Validator helpers (used by generated code)
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

/// Small, zero-dependency validator functions used by the
/// `#[model]` macro codegen. These are internal implementation details —
/// users never call these directly.
pub mod validators {
    use std::sync::LazyLock;
    use regex::Regex;

    /// Simple email validation: checks for `local@domain.tld` format.
    ///
    /// Not RFC 5322 compliant — but covers 99% of real-world emails.
    /// Can be swapped to a stricter implementation without user breakage.
    pub fn is_email(value: &str) -> bool {
        static RE: LazyLock<Regex> = LazyLock::new(|| {
            Regex::new(r"^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$").unwrap()
        });
        !value.is_empty() && RE.is_match(value)
    }

    /// Simple URL validation: checks for `scheme://host` format.
    pub fn is_url(value: &str) -> bool {
        static RE: LazyLock<Regex> = LazyLock::new(|| {
            Regex::new(r"^https?://[^\s/$.?#].[^\s]*$").unwrap()
        });
        RE.is_match(value)
    }

    /// Match a value against a regex pattern.
    pub fn matches_regex(value: &str, pattern: &str) -> bool {
        match Regex::new(pattern) {
            Ok(re) => re.is_match(value),
            Err(_) => false,
        }
    }
}
